### PR TITLE
Utility function io_uring_register_eventfd_async()

### PR DESCRIPTION
**Pull request by markpapadakis**

### CODE REVIEW

**Comment by axboe** [comment]
Looks good, just needs an entry in src/liburing.map as well for 0.6.

**Comment by markpapadakis** [comment]
@axboe Oops, forgot about liburing.map. Updated

**Comment by axboe** [comment]
Looks good now, but please do:

- Fold the two changes into one, it's one change, not two
- Make sure you have a commit body
- Make sure you have a Signed-off-by: at the bottom.

Here's an example of a commit for all of them:

https://git.kernel.dk/cgit/liburing/commit/?id=3d0842ce800fed9b79e6d445e1e563f31dd1aa82

**Comment by axboe** [comment]
Mark, there seems to be 4 commits here now. Can you collapse them into one change?

**Comment by markpapadakis** [comment]
Closing; will post another.

**Comment by axboe** [comment]
Superseded.

**Pull request closed without merging**
