### PR TITLE
[RFC][GIT PULL] Use GitHub Actions as CI (build only)

### PR DESCRIPTION
**Pull request by ammarfaizi2**
Hi Jens,

Following up about the CI in https://github.com/axboe/liburing/pull/425#issuecomment-914540396

I wired up the GitHub Actions CI. This will build the lib and tests. But it doesn't perform the `make runtests` due to kernel limitation reason.

There are 2 builds:
1) Build with GCC.
2) Build with Clang.

Both uses `CFLAGS="-Werror" CPPFLAGS="-Werror" CXXFLAGS="-Werror"` to make sure the build is totally clean from warnings.

Extra note:
There was very specific warning from clang that caused the build fail. It is fixed in commit 008ccce8858aa620315aba71e6d2b332dff5a39c ("build_with_clang.yml: fix clang build error -Wunused-command-line-argument").

The CI runs well on my fork repo, you can take a look here:
Build with Clang: https://github.com/ammarfaizi2/liburing/runs/3573032633
Build with GCC: https://github.com/ammarfaizi2/liburing/runs/3573032671

Please review. If you love it, please pull and remove the appveyor failing CI.

Adding Guillem to CC list..
Cc: @guillemj

```
----------------------------------------------------------------
The following changes since commit 8b087c441ed5f57e344b2ec1b26fcac42b42896a:

  test/runtests.sh: fix retrieving status (2021-09-10 10:17:31 -0600)

are available in the Git repository at:

  git://github.com/ammarfaizi2/liburing github-actions-ci

for you to fetch changes up to 008ccce8858aa620315aba71e6d2b332dff5a39c:

  build_with_clang.yml: fix clang build error -Wunused-command-line-argument (2021-09-11 09:45:55 +0700)

----------------------------------------------------------------
Ammar Faizi (3):
      .github/workflows: add build_with_gcc.yml
      .github/workflows: add build_with_clang.yml
      build_with_clang.yml: fix clang build error -Wunused-command-line-argument

 .github/workflows/build_with_clang.yml | 37 +++++++++++++++++++++++++++++++++++++
 .github/workflows/build_with_gcc.yml   | 32 ++++++++++++++++++++++++++++++++
 2 files changed, 69 insertions(+)
 create mode 100644 .github/workflows/build_with_clang.yml
 create mode 100644 .github/workflows/build_with_gcc.yml

```

### CODE REVIEW

**Comment by axboe** [comment]
Great, let's give this a whirl and see how it goes.

**Comment by guillemj** [comment]
> Following up about the CI in [#425 (comment)](https://github.com/axboe/liburing/pull/425#issuecomment-914540396)
> 
> I wired up the GitHub Actions CI. This will build the lib and tests. But it doesn't perform the `make runtests` due to kernel limitation reason.

Ah sorry, had prepared something that night, but run out of time to test so didn't end up submitting it. That was https://github.com/guillemj/liburing/commit/de4f9b875607cb95babec29c9b4ba0bd549722ee that just pushed earlier today, which obviously failed everywhere. :)

I've improved those a bit now locally to make them pass. I guess I'll split the shellcheck one, and if there's interest I could prep another one to simplify the two builds into the matrix one I had there (but with a working version. :)

The runtest just timed out, not sure whether that was due to running as root. Will try as user, but still ignoring the exit code, but not sure that's worth it, though.

> Extra note:
> There was very specific warning from clang that caused the build fail. It is fixed in commit [008ccce](https://github.com/axboe/liburing/commit/008ccce8858aa620315aba71e6d2b332dff5a39c) ("build_with_clang.yml: fix clang build error -Wunused-command-line-argument").

I think, but need to check, the warning was valid. I've had locally a patch to cleanup the LDFLAGS usage, which I think would also fix that. Will get that cleaned up in any case and published for review.

**Comment by axboe** [comment]
I wouldn't both with the runtests for now, they are only useful if you control the kernel as well.

**Comment by ammarfaizi2** [comment]
> I've improved those a bit now locally to make them pass. I guess I'll split the shellcheck one, and if there's interest I could prep another one to simplify the two builds into the matrix one I had there (but with a working version. :)

Sounds good, please go ahead.

> The runtest just timed out, not sure whether that was due to running as root. Will try as user, but still ignoring the exit code, but not sure that's worth it, though.

Not worth it, the test result depends on the exit code. There is no point running them if we ignore the exit code.

> I think, but need to check, the warning was valid. I've had locally a patch to cleanup the LDFLAGS usage, which I think would also fix that. Will get that cleaned up in any case and published for review.

I will be looking forward for it.

Also there are `make-debs.sh` and `debian` directory on liburing repo. I don't really know what kind of build they do. Are they still maintained? Any plan to add that build to CI as well?

**Comment by guillemj** [comment]
> Also there are `make-debs.sh` and `debian` directory on liburing repo. I don't really know what kind of build they do. Are they still maintained? Any plan to add that build to CI as well?

Right, these are intended for Debian package builds. When I packaged this for Debian I started the packaging from scratch, which I maintain elsewhere (https://git.hadrons.org/cgit/debian/pkgs/liburing.git), as it seemed easier than to fix all the issues present here.

So, the packaging present here seems outdated and a bit buggy, but I've been hesitant to send a removal MR, as I'm not sure who might be using that, and whether that might inconvenience them? But perhaps now that liburing is present in a Debian stable release, and also as a backport in the oldstable release this could go now? I'm happy to prepare a MR for that. :)

**Comment by ammarfaizi2** [comment]
> > Also there are `make-debs.sh` and `debian` directory on liburing repo. I don't really know what kind of build they do. Are they still maintained? Any plan to add that build to CI as well?
> 
> Right, these are intended for Debian package builds. When I packaged this for Debian I started the packaging from scratch, which I maintain elsewhere (https://git.hadrons.org/cgit/debian/pkgs/liburing.git), as it seemed easier than to fix all the issues present here.

Let's CC them first. If they agree or don't reply for reasonable time, then it is probably fine to start wiring up a pull request for that.

> So, the packaging present here seems outdated and a bit buggy, but I've been hesitant to send a removal MR, as I'm not sure who might be using that, and whether that might inconvenience them? But perhaps now that liburing is present in a Debian stable release, and also as a backport in the oldstable release this could go now? I'm happy to prepare a MR for that. :)

Checking that directory, the average files on there are not touched for 2 years. Not sure these are still maintained or not. If they're not, let's make them alive again.

Adding Changcheng as the author...
Cc: @changchengx

**Comment by guillemj** [comment]
> Checking that directory, the average files on there are not touched for 2 years. Not sure these are still maintained or not. If they're not, let's make them alive again.

Just to clarify my position, if someone is using this from upstream and wants to keep them fresh, I don't mind greatly. This is just slightly inconvenient when preparing new releases for Debian as then I need to remove the debian/ directory to replace it with my own, but nothing major. I think I'm also unlikely to keep these up-to-date myself when preparing the updates in Debian, as that's just an additional inconvenience. :)

**Comment by axboe** [comment]
Let's check with @metze-samba as he worked on this originally.

**Comment by guillemj** [comment]
> Right, these are intended for Debian package builds. When I packaged this for Debian I started the packaging from scratch, which I maintain elsewhere (https://git.hadrons.org/cgit/debian/pkgs/liburing.git), as it seemed easier than to fix all the issues present here.

Sorry, it seems I botched the meaning when reordering the sentences, which could be misinterpreted. I meant to say that I started from scratch because that seemed easier, and I maintain all Debian packaging (even for things where I'm upstream) in separate git repos out of personal workflow/policy. (But as I've mentioned not an argument for or against from my side, though. :)

**Comment by changchengx** [comment]
@ammarfaizi2 The debian package script supports to build debian package from soure code directly. Or, developers have to use therir own method to build debian package. It's like the rpm spec file here. Please help fix the error if you find the error in the script. All in all, the target is to run "make-deb.sh" to build out debian package directly.

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 The debian package script supports to build debian package from soure code directly. Or, developers have to use therir own method to build debian package. It's like the rpm spec file here. Please help fix the error if you find the error in the script. All in all, the target is to run "make-deb.sh" to build out debian package directly.

Tried to run `make-debs.sh`, got the following error. Not sure about the fix, @guillemj any idea?

```
     CC statx
     CXX sq-full-cpp
lto1: fatal error: bytecode stream in file ‘helpers.o’ generated with LTO version 9.3 instead of the expected 11.0
compilation terminated.
lto-wrapper: fatal error: g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:166: sq-full-cpp] Error 1
make[2]: Leaving directory '/tmp/release/Ubuntu/liburing/liburing-2.1/test'
make[1]: *** [Makefile:13: all] Error 2
make[1]: Leaving directory '/tmp/release/Ubuntu/liburing/liburing-2.1'
make: *** [debian/rules:23: build-arch] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

**Comment by ammarfaizi2** [comment]
> Tried to run `make-debs.sh`, got the following error. Not sure about the fix, @guillemj any idea?
> 
> ```
>      CC statx
>      CXX sq-full-cpp
> lto1: fatal error: bytecode stream in file ‘helpers.o’ generated with LTO version 9.3 instead of the expected 11.0
> compilation terminated.
> lto-wrapper: fatal error: g++ returned 1 exit status
> compilation terminated.
> /usr/bin/ld: error: lto-wrapper failed
> collect2: error: ld returned 1 exit status
> make[2]: *** [Makefile:166: sq-full-cpp] Error 1
> make[2]: Leaving directory '/tmp/release/Ubuntu/liburing/liburing-2.1/test'
> make[1]: *** [Makefile:13: all] Error 2
> make[1]: Leaving directory '/tmp/release/Ubuntu/liburing/liburing-2.1'
> make: *** [debian/rules:23: build-arch] Error 2
> dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
> debuild: fatal error at line 1182:
> dpkg-buildpackage -us -uc -ui failed
> ```

It seems I didn't properly configure my environment, will investigate it further.

**Pull request merged**
