### PR TITLE
[GIT PULL] src/queue: introduce io_uring_submit_and_get_events_and_wait

### PR DESCRIPTION
**Pull request by evyatark2**
There wasn't a good option to submit requests with IORING_ENTER_GETEVENTS while also waiting for completion with a single syscall.

This patch introduces io_uring_submit_and_get_events_and_wait which does that.

----
## git request-pull output:
```
The following changes since commit 1419174a6c483f731747811084cf7449769205a1:

  test/regbuf-clone: test dummy ubuf cloning (2024-10-16 07:17:27 -0600)

are available in the Git repository at:

  https://github.com/evyatark2/liburing.git getevents-and-wait

for you to fetch changes up to 7c2dda0f2178a78e9c3ad79461468c4eb6dbf8ed:

  src/queue: introduce io_uring_submit_and_get_events_and_wait (2024-10-17 22:17:13 +0200)

----------------------------------------------------------------
Evyatar Stalinsky (1):
      src/queue: introduce io_uring_submit_and_get_events_and_wait

 man/io_uring_submit_and_get_events_and_wait.3 | 35 +++++++++++++++++++++++++++++++++++
 src/include/liburing.h                        |  1 +
 src/queue.c                                   | 13 +++++++++----
 3 files changed, 45 insertions(+), 4 deletions(-)
 create mode 100644 man/io_uring_submit_and_get_events_and_wait.3

```
----
<details>
<summary>Click to show/hide pull request guidelines</summary>

## Pull Request Guidelines
1. To make everyone easily filter pull request from the email
notification, use `[GIT PULL]` as a prefix in your PR title.
```
[GIT PULL] Your Pull Request Title
```
2. Follow the commit message format rules below.
3. Follow the Linux kernel coding style (see: https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst).

### Commit message format rules:
1. The first line is title (don't be more than 72 chars if possible).
2. Then an empty line.
3. Then a description (may be omitted for truly trivial changes).
4. Then an empty line again (if it has a description).
5. Then a `Signed-off-by` tag with your real name and email. For example:
```
Signed-off-by: Foo Bar <foo.bar@gmail.com>
```

The description should be word-wrapped at 72 chars. Some things should
not be word-wrapped. They may be some kind of quoted text - long
compiler error messages, oops reports, Link, etc. (things that have a
certain specific format).

Note that all of this goes in the commit message, not in the pull
request text. The pull request text should introduce what this pull
request does, and each commit message should explain the rationale for
why that particular change was made. The git tree is canonical source
of truth, not github.

Each patch should do one thing, and one thing only. If you find yourself
writing an explanation for why a patch is fixing multiple issues, that's
a good indication that the change should be split into separate patches.

If the commit is a fix for an issue, add a `Fixes` tag with the issue
URL.

Don't use GitHub anonymous email like this as the commit author:
```
123456789+username@users.noreply.github.com
```

Use a real email address!

### Commit message example:
```
src/queue: don't flush SQ ring for new wait interface

If we have IORING_FEAT_EXT_ARG, then timeouts are done through the
syscall instead of by posting an internal timeout. This was done
to be both more efficient, but also to enable multi-threaded use
the wait side. If we touch the SQ state by flushing it, that isn't
safe without synchronization.

Fixes: https://github.com/axboe/liburing/issues/402
Signed-off-by: Jens Axboe <axboe@kernel.dk>
```

</details>

----
## By submitting this pull request, I acknowledge that:
1. I have followed the above pull request guidelines.
2. I have the rights to submit this work under the same license.
3. I agree to a Developer Certificate of Origin (see https://developercertificate.org for more information).

### CODE REVIEW

**Comment by isilence** [comment]
> There wasn't a good option to submit requests with IORING_ENTER_GETEVENTS while also waiting for completion with a single syscall.

There is, that's called `io_uring_submit_and_wait`. In general "wait" is a superset of "getevents",

**Comment by isilence** [comment]
Or to put it differently, `getevents` is `wait(nr=0)`.

**Comment by axboe** [comment]
Yeah was going to comment what Pavel said - io_uring_sumit_and_wait() already does all of this.

**Comment by evyatark2** [comment]
Oh, I didn't realize that flags gets a `IORING_ENTER_GETEVENTS` if `wait_nr > 0` in `__io_uring_submit`.

**Pull request closed without merging**
