### PR TITLE
setup.c: handmade fls -> __builtin_clz

### PR DESCRIPTION
**Pull request by Tindarid**
I think such change makes it more clear

### CODE REVIEW

**Comment by axboe** [comment]
Why not just use __builtin_ffs() instead?

**Comment by axboe** [comment]
OK I'm an idiot! Misremembered what it was doing. I'm fine with your change. But let's make it:

```
if (!x)
    return 0;
return 8 * sizeof(int) - __builtin_clz(x);
```

I hate reading ternarys.

**Comment by Tindarid** [comment]
fixed

**Comment by axboe** [comment]
Thanks!

**Pull request merged**
