### PR TITLE
.github/workflows/build.yml: Pass -g -O2 -Wall -Wextra explicitly

### PR DESCRIPTION
**Pull request by guillemj**
As these flags are marked as optional now they get reset when we pass
explicit flags.

Cc: @ammarfaizi2

### CODE REVIEW

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
Don't forget `Signed-off-by` tag. Also, can we include `-Wextra`?

**Comment by axboe** [comment]
> Don't forget Signed-off-by tag. Also, can we include -Wextra?

Agree on both of those.

**Review by ammarfaizi2 — APPROVED** [review]

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
Dismiss the approval, we got this

```
gcc -Werror -D_GNU_SOURCE -I../src/include/ -g -O2 -Wall -Wextra -Werror -o io_uring-test io_uring-test.c  -L../src/ -luring
gcc -Werror -D_GNU_SOURCE -I../src/include/ -g -O2 -Wall -Wextra -Werror -o io_uring-cp io_uring-cp.c  -L../src/ -luring
io_uring-cp.c: In function ‘copy_file’:
io_uring-cp.c:154:17: error: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Werror=sign-compare]
  154 |   if (had_reads != reads) {
      |                 ^~
io_uring-cp.c:197:24: error: comparison of integer expressions of different signedness: ‘__s32’ {aka ‘int’} and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  197 |    } else if (cqe->res != data->iov.iov_len) {
      |                        ^~
gcc -Werror -D_GNU_SOURCE -I../src/include/ -g -O2 -Wall -Wextra -Werror -o link-cp link-cp.c  -L../src/ -luring
cc1: all warnings being treated as errors
make[1]: *** [Makefile:26: io_uring-cp] Error 1
make[1]: *** Waiting for unfinished jobs....
link-cp.c: In function ‘copy_file’:
link-cp.c:128:18: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘off_t’ {aka ‘long int’} [-Werror=sign-compare]
  128 |    if (this_size > insize)
      |                  ^
link-cp.c:136:20: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
  136 |   if (has_inflight != inflight)
      |                    ^~
link-cp.c:143:19: error: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Werror=sign-compare]
  143 |   while (inflight >= depth) {
      |                   ^~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:26: link-cp] Error 1
make[1]: Leaving directory '/home/runner/work/liburing/liburing/examples'
make: *** [Makefile:14: all] Error 2
```

**Comment by guillemj** [comment]
Ah, sorry rushed this one out previously, and it failed too now, will prep fixes for the new errors.

**Review by ammarfaizi2 — APPROVED** [review]

**Pull request merged**
