### PR TITLE
[GIT PULL] Allow configure script to fail if there are bash errors on the way.

### PR DESCRIPTION
**Pull request by romange**
Signed-off-by: Roman Gershman  <romange@gmail.com>

For poorly configured environments, `configure` may fail but will still exit with code 0.
This, in turn, causes cryptic build errors later (happened to me on alpine linux without coreutils package installed).

----
## git request-pull output:
```
The following changes since commit 3b52ae980c41b420592e3005199041890a56d6dc:

  test/fixed-reuse: test that linked file slot reuse is correct (2022-03-30 11:33:38 -0600)

are available in the Git repository at:

  https://github.com/romange/liburing.git 

for you to fetch changes up to 994f8d39ba42ea3171cb3bbee55ea08e6dda904b:

  configure script should fail if any of the underlying commands fail. (2022-04-01 15:04:52 +0300)

----------------------------------------------------------------
Roman Gershman (1):
      configure script should fail if any of the underlying commands fail.

 configure | 2 ++
 1 file changed, 2 insertions(+)

```
----
<details>
<summary>Click to show/hide pull request guidelines</summary>

## Pull Request Guidelines
1. To make everyone easily filter pull request from the email
notification, use `[GIT PULL]` as a prefix in your PR title.
```
[GIT PULL] Your Pull Request Title
```
2. Follow the commit message format rules below.
3. Follow the Linux kernel coding style (see: https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst).

### Commit message format rules:
1. The first line is title (don't be more than 72 chars if possible).
2. Then an empty line.
3. Then a description (may be omitted for truly trivial changes).
4. Then an empty line again (if it has a description).
5. Then a `Signed-off-by` tag with your real name and email. For example:
```
Signed-off-by: Foo Bar <foo.bar@gmail.com>
```

The description should be word-wrapped at 72 chars. Some things should
not be word-wrapped. They may be some kind of quoted text - long
compiler error messages, oops reports, Link, etc. (things that have a
certain specific format).

Note that all of this goes in the commit message, not in the pull
request text. The pull request text should introduce what this pull
request does, and each commit message should explain the rationale for
why that particular change was made. The git tree is canonical source
of truth, not github.

Each patch should do one thing, and one thing only. If you find yourself
writing an explanation for why a patch is fixing multiple issues, that's
a good indication that the change should be split into separate patches.

If the commit is a fix for an issue, add a `Fixes` tag with the issue
URL.

Don't use GitHub anonymous email like this as the commit author:
```
123456789+username@users.noreply.github.com
```

Use a real email address!

### Commit message example:
```
src/queue: don't flush SQ ring for new wait interface

If we have IORING_FEAT_EXT_ARG, then timeouts are done through the
syscall instead of by posting an internal timeout. This was done
to be both more efficient, but also to enable multi-threaded use
the wait side. If we touch the SQ state by flushing it, that isn't
safe without synchronization.

Fixes: https://github.com/axboe/liburing/issues/402
Signed-off-by: Jens Axboe <axboe@kernel.dk>
```

</details>

----
## By submitting this pull request, I acknowledge that:
1. I have followed the above pull request guidelines.
2. I have the rights to submit this work under the same license.
3. I agree to a Developer Certificate of Origin (see https://developercertificate.org for more information).

### CODE REVIEW

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
> For poorly configured environments, `configure` may fail but will still exit with code 0. This, in turn, causes cryptic build errors later (happened to me on alpine linux without coreutils package installed).

This explanation should also go into the commit message.

Another problem reported by the GitHub bot, this patch breaks the nolibc build, not sure what happens.

**Comment by romange** [comment]
Maybe it has already been broken but "set -e" exposed it?

**Comment by ammarfaizi2** [comment]
> Maybe it has already been broken but "set -e" exposed it?

Yeah, makes sense to me, it would be great if you can fix that as well instead of leaving the GitHub bot CI red.

**Comment by romange** [comment]
Hi Ammar, unfortunately i wont be able to fix it, because i do not have
access to that type of environment at hand. I can close the PR if you
prefer.

**Comment by ammarfaizi2** [comment]
> Hi Ammar, unfortunately i wont be able to fix it, because i do not have access to that type of environment at hand. I can close the PR if you prefer.

I will try to fix it and cherry-pick your commit. So yeah, let's close this. I will mention you in my PR later if I can figure it out.

**Comment by ammarfaizi2** [comment]
> > Hi Ammar, unfortunately i wont be able to fix it, because i do not have access to that type of environment at hand. I can close the PR if you prefer.
> 
> I will try to fix it and cherry-pick your commit. So yeah, let's close this. I will mention you in my PR later if I can figure it out.

OK, I found the culprit.

In the configure script, we have:
```
optarg=$(expr "x$opt" : 'x[^=]*=\(.*\)')
```
If the $opt doesn't match with that regex, it will give exit code 1. So it will break any argument that doesn't have value.

Like `--help` and `--nolibc` for example.

I will send a PR to fix it soon.

**Pull request closed without merging**
