### PR TITLE
[GIT PULL] Clarify behaviour of offset in `prep_read`/`prep_write`.

### PR DESCRIPTION
**Pull request by ioquatix**
----
## git request-pull output:
```
The following changes since commit 7233a8753cb7a4a137cdc5e534bb31fb2a0d53fd:

  test/getdents: ignore run if argument specified (2021-12-22 19:54:45 -0700)

are available in the Git repository at:

  git@github.com:ioquatix/liburing.git man-page-offset-clarification

for you to fetch changes up to 9ec56b9fb31d9f77fc23113ceda27d7b4cbad19e:

  Clarify behaviour of offset in `prep_read`/`prep_write`. (2021-12-23 17:29:24 +1300)

----------------------------------------------------------------
Samuel Williams (1):
      Clarify behaviour of offset in `prep_read`/`prep_write`.

 man/io_uring_prep_read.3    | 17 +++++++++++++++--
 man/io_uring_prep_readv.3   | 16 +++++++++++++++-
 man/io_uring_prep_readv2.3  | 19 +++++++++++++++++--
 man/io_uring_prep_write.3   | 17 +++++++++++++++--
 man/io_uring_prep_writev.3  | 18 ++++++++++++++++--
 man/io_uring_prep_writev2.3 | 21 +++++++++++++++++----
 6 files changed, 95 insertions(+), 13 deletions(-)
```
----
<details>
<summary>Click to show/hide pull request guidelines</summary>

## Pull Request Guidelines
1. To make everyone easily filter pull request from the email
notification, use `[GIT PULL]` as a prefix in your PR title.
```
[GIT PULL] Your Pull Request Title
```
2. Follow the commit message format rules below.
3. Follow the Linux kernel coding style (see: https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst).

### Commit message format rules:
1. The first line is title (don't be more than 72 chars if possible).
2. Then an empty line.
3. Then a description (may be omitted for truly trivial changes).
4. Then an empty line again (if it has a description).
5. Then a `Signed-off-by` tag with your real name and email. For example:
```
Signed-off-by: Foo Bar <foo.bar@gmail.com>
```

The description should be word-wrapped at 72 chars. Some things should
not be word-wrapped. They may be some kind of quoted text - long
compiler error messages, oops reports, Link, etc. (things that have a
certain specific format).

Note that all of this goes in the commit message, not in the pull
request text. The pull request text should introduce what this pull
request does, and each commit message should explain the rationale for
why that particular change was made. The git tree is canonical source
of truth, not github.

Each patch should do one thing, and one thing only. If you find yourself
writing an explanation for why a patch is fixing multiple issues, that's
a good indication that the change should be split into separate patches.

If the commit is a fix for an issue, add a `Fixes` tag with the issue
URL.

Don't use GitHub anonymous email like this as the commit author:
```
123456789+username@users.noreply.github.com
```

Use a real email address!

### Commit message example:
```
src/queue: don't flush SQ ring for new wait interface

If we have IORING_FEAT_EXT_ARG, then timeouts are done through the
syscall instead of by posting an internal timeout. This was done
to be both more efficient, but also to enable multi-threaded use
the wait side. If we touch the SQ state by flushing it, that isn't
safe without synchronization.

Fixes: https://github.com/axboe/liburing/issues/402
Signed-off-by: Jens Axboe <axboe@kernel.dk>
```

</details>

----
## By submitting this pull request, I acknowledge that:
1. I have followed the above pull request guidelines.
2. I have the rights to submit this work under the same license.
3. I agree to a Developer Certificate of Origin (see https://developercertificate.org for more information).

### CODE REVIEW

**Comment by ioquatix** [comment]
@axboe I thought we could clarify the offset argument. Let me know what you think.

**Comment by axboe** [comment]
I'm fine with clarifying it, but file descriptor is well understood and means any file type. Changing it to object makes it a lot less understandable imho.

**Comment by axboe** [comment]
The non file descriptor changes look great, would you mind doing just those?

**Comment by ioquatix** [comment]
> I'm fine with clarifying it, but file descriptor is well understood and means any file type. Changing it to object makes it a lot less understandable imho.

I was following the BSD man pages which use the term object but I see the Linux man pages are different:

https://www.freebsd.org/cgi/man.cgi?sektion=2&query=read

Not sure which one makes more sense.

**Comment by ioquatix** [comment]
I think calling everything a "file" is confusing. I think this is probably why BSD uses the term object, since there are a lots of things that can be referenced by a "file descriptor". In my own code, I generally don't refer to it as "fd" or "file descriptor" but now just refer to it as "descriptor" to try and avoid this cognitive overload.

**Comment by ioquatix** [comment]
I rewrote it following Linux conventions which makes more sense.

**Comment by axboe** [comment]
Looks good, thanks!

**Pull request merged**
